### ISSUE TITLE
Algunas soluciones que pueden ser implementadas 

### ISSUE THREAD

**Issue by Stoudemire** [joseluis2g/my-nostalrius#14]
https://github.com/TwistedScorpio/Nostalrius/issues/3

https://github.com/TwistedScorpio/Nostalrius/issues/4

https://github.com/TwistedScorpio/Nostalrius/issues/10

**Comment by angeliker** [comment]
no quise habrir otro issue esto se trata de compilar en linux este es el error k me tira
`/home/Tibiana/src/combat.cpp: In static member function ‘static bool Combat::clo                                                                                        seAttack(Creature*, Creature*, fightMode_t)’:
/home/Tibiana/src/combat.cpp:887:38: error: suggest parentheses around ‘&&’ with                                                                                        in ‘||’ [-Werror=parentheses]
    if (hit || -totalDamage > defense && (randTest == 5 * (randTest / 5))) {
                                      ^
/home/Tibiana/src/commands.cpp:50:1: error: ‘s_defcommands’ does not name a type
 s_defcommands Commands::defined_commands[] = {
 ^
/home/Tibiana/src/commands.cpp:61:1: error: ‘Commands’ does not name a type
 Commands::Commands()
 ^
/home/Tibiana/src/commands.cpp:69:1: error: ‘Commands’ does not name a type
 Commands::~Commands()
 ^
/home/Tibiana/src/commands.cpp:76:6: error: ‘Commands’ has not been declared
 bool Commands::loadFromXml()
      ^
/home/Tibiana/src/commands.cpp: In function ‘bool loadFromXml()’:
/home/Tibiana/src/commands.cpp:92:13: error: ‘commandMap’ was not declared in th                                                                                        is scope
   auto it = commandMap.find(cmdAttribute.as_string());
             ^
/home/Tibiana/src/commands.cpp:98:3: error: ‘Command’ was not declared in this s                                                                                        cope
   Command* command = it->second;
   ^
/home/Tibiana/src/commands.cpp:98:12: error: ‘command’ was not declared in this                                                                                         scope
   Command* command = it->second;
            ^
/home/Tibiana/src/commands.cpp:120:10: error: ‘class Game’ has no member named ‘                                                                                        addCommandTag’
   g_game.addCommandTag(it->first.front());
          ^
/home/Tibiana/src/commands.cpp: At global scope:
/home/Tibiana/src/commands.cpp:125:6: error: ‘Commands’ has not been declared
 bool Commands::reload()
      ^
/home/Tibiana/src/commands.cpp: In function ‘bool reload()’:
/home/Tibiana/src/commands.cpp:127:24: error: ‘commandMap’ was not declared in t                                                                                        his scope
  for (const auto& it : commandMap) {
                        ^
/home/Tibiana/src/commands.cpp:128:3: error: ‘Command’ was not declared in this                                                                                         scope
   Command* command = it.second;
   ^
/home/Tibiana/src/commands.cpp:128:12: error: ‘command’ was not declared in this                                                                                         scope
   Command* command = it.second;
            ^
/home/Tibiana/src/commands.cpp:134:9: error: ‘class Game’ has no member named ‘r                                                                                        esetCommandTag’
  g_game.resetCommandTag();
         ^
/home/Tibiana/src/commands.cpp: At global scope:
/home/Tibiana/src/commands.cpp:138:6: error: ‘Commands’ has not been declared
 bool Commands::exeCommand(Player& player, const std::string& cmd)
      ^
/home/Tibiana/src/commands.cpp: In function ‘bool exeCommand(Player&, const stri                                                                                        ng&)’:
/home/Tibiana/src/commands.cpp:152:12: error: ‘commandMap’ was not declared in t                                                                                        his scope
  auto it = commandMap.find(str_command);
            ^
/home/Tibiana/src/commands.cpp:157:2: error: ‘Command’ was not declared in this                                                                                         scope
  Command* command = it->second;
  ^
/home/Tibiana/src/commands.cpp:157:11: error: ‘command’ was not declared in this                                                                                         scope
  Command* command = it->second;
           ^
/home/Tibiana/src/commands.cpp:167:2: error: ‘CommandFunc’ was not declared in t                                                                                        his scope
  CommandFunc cfunc = command->f;
  ^
/home/Tibiana/src/commands.cpp:167:14: error: expected ‘;’ before ‘cfunc’
  CommandFunc cfunc = command->f;
              ^
/home/Tibiana/src/commands.cpp:168:3: error: invalid use of ‘this’ in non-member                                                                                         function
  (this->*cfunc)(player, str_param);
   ^
/home/Tibiana/src/commands.cpp:168:10: error: ‘cfunc’ was not declared in this s                                                                                        cope
  (this->*cfunc)(player, str_param);
          ^
/home/Tibiana/src/commands.cpp: At global scope:
/home/Tibiana/src/commands.cpp:189:6: error: ‘Commands’ has not been declared
 void Commands::reloadInfo(Player& player, const std::string& param)
      ^
/home/Tibiana/src/commands.cpp:243:6: error: ‘Commands’ has not been declared
 void Commands::sellHouse(Player& player, const std::string& param)
      ^
/home/Tibiana/src/commands.cpp:296:6: error: ‘Commands’ has not been declared
 void Commands::forceRaid(Player& player, const std::string& param)
      ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/tfs.dir/src/combat.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/tfs.dir/src/commands.cpp.o] Error 1
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by joseluis2g** [comment]
thats because cmake files includes commands, im going to try to add travis ci to fix the unix compilations

**Comment by joseluis2g** [comment]
Arregle los problemas con travis, ahora deberías poder compilar en linux sin ni un problema. Actualiza todos los documentos antes de compilar.

**Comment by Olddies710** [comment]
nose si es problema de los sprites pero cuando estas debajo de una escalera i un monster te da 1 hit se desaparece la escalera :o:

**Comment by joseluis2g** [comment]
No me ha sucedido nunca @angeliker, podrías hacer un video al respecto.

**Comment by Stoudemire** [comment]
> nose si es problema de los sprites pero cuando estas debajo de una escalera i un monster te da 1 hit se desaparece la escalera ⭕️

tampoco me ha sucedido
https://gyazo.com/b756e42aead72ec3d19d8ccb9f06124f

**Comment by Olddies710** [comment]
mmm puede ser culpa del otc? @Stoudemire estas usando otc o normal cliente

**Comment by Stoudemire** [comment]
estoy usando tibianic client (cipsoft client)

**Comment by Stoudemire** [comment]
> mmm puede ser culpa del otc? @Stoudemire estas usando otc o normal cliente

estoy usando tibianic client

**Comment by Olddies710** [comment]
> > mmm puede ser culpa del otc? @Stoudemire estas usando otc o normal cliente
> 
> estoy usando tibianic client

oh ya entonces kisas sea eso ni modo entonces xd

**Comment by Stoudemire** [comment]
probaré con mi otc 

edit:
Si, con otclient desaparecen las ladders, pero eso es un problema de otc

**Comment by Olddies710** [comment]
si si solo keria estar seguro k es el otc
