### ISSUE TITLE
perdida de items en casas

### ISSUE THREAD

**Issue by Stoudemire** [joseluis2g/my-nostalrius#15]
al colocar decoración en paredes como por ejemplo tapestries y luego hacer un restart los items desaparecen
hay alguna manera de solucionar esto sin tener que agregar manualmente los house tiles sobre las walls en cada casa? _(861 en total)_
o hacer algo relacionado con esto https://otland.net/threads/save-movable-items-on-map-to-database.253034/

**Comment by joseluis2g** [comment]
lamentablemente no hay otra solución puesto que si el tile no tiene dueño entonces la pared de la casa tampoco es de nadie. Solo agregar cada sqm a su casa correspondiente. No es difícil, solo tedioso.

**Comment by joseluis2g** [comment]
y el post que agregaste no tiene que ver con lo que preguntas. En el post se guardarian todos los items siempre.

**Comment by Stoudemire** [comment]
tibia funciona de esa manera, los items del mapa no se y tambien los de las casas

**Comment by joseluis2g** [comment]
osea se guardaria toda la basura por siempre y para siempre. Tibia divide el mapa y lo guarda por sectores, si los sectores del mapa no tienen gente en determinado momento entonces el sector se limpia. Eso aun no es posible en los ots que utilizan otbm, como este.

**Comment by Stoudemire** [comment]
Cierto, buen punto, entonces la unica solución posible en este caso será agregar manualmente los house tiles a cada casa
