### ISSUE TITLE
creature push stack

### ISSUE THREAD

**Issue by emil92b** [joseluis2g/my-nostalrius#24]
should push last player in stack not first aswell

**Comment by joseluis2g** [comment]
This is related to the uh trap, isnt it?

**Comment by emil92b** [comment]
it act the same like it, just this is for push monster/player instead of use rune on them

**Comment by joseluis2g** [comment]
Im going to check it.

**Comment by emil92b** [comment]
i confirmed it already on realots experimental, and its reversed on nostalrius repo

**Comment by joseluis2g** [comment]
can you test this?
https://github.com/joseluis2g/my-nostalrius/commit/691084175aa33e88b5c3757315ccca4957c37529

**Comment by ghost** [comment]
no need for config shit and extra stuff

**game.cpp**
`thing = tile->getTopVisibleCreature(player);`
to 
`thing = tile->getBottomVisibleCreature(player);`


**tile.cpp**
`const Creature* Tile::getBottomCreature() const`
to
`Creature* Tile::getBottomCreature() const`


`const Creature* Tile::getBottomVisibleCreature(const Creature* creature) const`
to
`Creature* Tile::getBottomVisibleCreature(const Creature* creature) const`

**tile.h**
`const Creature* getBottomCreature() const;`
to
`Creature* getBottomCreature() const;`


`const Creature* getBottomVisibleCreature(const Creature* creature) const;`
to
`Creature* getBottomVisibleCreature(const Creature* creature) const;`

works perfect for me, not sure if theres any side effects tho, mby you can list that out ;P

is there a reason why bottomCreature was a const and not topCreature?

**Comment by joseluis2g** [comment]
That would require a few extra changes like luascript but yeah you can do that, I just didnt wanted to touch anything else, but your solution seems cleaner, Im going to do those changes.

**Comment by joseluis2g** [comment]
btw, is it working as you want?

**Comment by ghost** [comment]
what luascript changes? can you post

yeah its working
