### ISSUE TITLE
Wrong missile HMM and LMM

### ISSUE THREAD

**Issue by renanluis90** [joseluis2g/my-nostalrius#26]
combat:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_ENERGY)

Here have this wrong distance effect, is not the same of magicwall distance effect, someone can test 

combat:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_FIRE) <--- this?

**Comment by joseluis2g** [comment]
Can you test with the current build?
Use appveyor if you cant compile.

**Comment by renanluis90** [comment]
No need compile, is on runes folder, heavy magic missile.lua and light magic missile.lua, i cant test now, im using mobile

**Comment by Stoudemire** [comment]
> combat:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_ENERGY)
> 
> Here have this wrong distance effect, is not the same of magicwall distance effect, someone can test
> 
> combat:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_FIRE) <--- this?

confirmed, just replace it with this
setCombatParam(combat, COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_FIRE)

**Comment by joseluis2g** [comment]
can you create a pr?
