### ISSUE TITLE
now we can use mana fluids for example in others players/monsters

### ISSUE THREAD

**Issue by renanluis90** [joseluis2g/my-nostalrius#29]
this is wrong, in ReaLOTS we can't use fluids on monsters/npcs/others players...

I saw a modification in file fluids.lua, to not use in npcs... right!  but we can use this

Solution.
**if target:isCreature() and target == player then**    <------
		if item:getFluidType() == FLUID_NONE then
			player:sendCancelMessage("It is empty.")

This can solve all the problems.

**Comment by Stoudemire** [comment]
Confirmed, This solution solve this issue
https://github.com/joseluis2g/my-nostalrius/issues/3#issuecomment-459361309
