### ISSUE TITLE
uh trap & height stack block 

### ISSUE THREAD

**Issue by Stoudemire** [joseluis2g/my-nostalrius#3]
agregue el height stack block & uh trap
de aqui saque los codigos

Fixed bed, added UH-trap, not-pushing yourself on stacked items with … · mattyx14/theforgottenserver-7.4@5af1795 (https://github.com/mattyx14/theforgottenserver-7.4/commit/5af1795c7893f892c1f0e8f4bfd0b8d9872e5d65)

durante la compilacion no dio ningun error y al momento de probar in game no funciono el uh trap
la opcion para habilitar o deshabilitar height stack block en config.lua no sirve, height stack block siempre esta activo y no se puede desactivar

- [x] UH Trap + config optional
- [x] Stack Height + config optional

**Comment by joseluis2g** [comment]
que es el height stack block?

**Comment by joseluis2g** [comment]
y me podrías explicar un poco más el tema de la uh trap, supuestamente la uh trap funciona cuando tu como player usas una runa en ti (sd, uh, ih, etc) y hay un stack de personas, en el stack de personas la última persona que ingresa al stack es la que debería recibir la runa, cierto?

**Comment by Stoudemire** [comment]
> y me podrías explicar un poco más el tema de la uh trap, supuestamente la uh trap funciona cuando tu como player usas una runa en ti (sd, uh, ih, etc) y hay un stack de personas, en el stack de personas la última persona que ingresa al stack es la que debería recibir la runa, cierto?

Si, Exacto, asi mismo como describes tú es como funciona el uh trap
https://www.youtube.com/watch?v=jCChhnIG22M

El height stack block o parcel stack block

1 Parcels, boxes etc. = puedes caminar encima de ella
2+ Parcels, boxes etc. = no puedes caminar encima de ellas

**Comment by joseluis2g** [comment]
podrías probar esto?
https://github.com/joseluis2g/my-nostalrius/commit/81cb96295a7d1586e5235a240ebb2a7c66280fc4

**Comment by Stoudemire** [comment]
se bugea al subir al estar stackeados, al subir o bajar 
https://gyazo.com/b246b5c906179613b57b950095cead36

**Comment by joseluis2g** [comment]
bueno, el tema es que al parecer no se puede arreglar el tema visual, pero el tema de la mecanica si se puede arreglar, que la runa no la use en la primera persona, si no en la última.

**Comment by joseluis2g** [comment]
y con el aspecto visual me refiero a que si te das cuenta, en el video la primera persona que cae al hoyo es tambien visualmente la primera persona que se ve, a pesar de no ser la  última en caer.

**Comment by Stoudemire** [comment]
claro, lo importante es arreglar el tema de la mecanica (que la runa no la use en la primera persona, si no en la última)

**Comment by joseluis2g** [comment]
heigh stack: https://github.com/joseluis2g/my-nostalrius/commit/93e019428ed3b2d25d4b73f147a963beb185c706
podrías probarlo?

**Comment by Stoudemire** [comment]
`1>c:\forgottenserver\src\game.cpp(655): error C2039: 'getHeight': is not a member of 'Tile'
1>c:\forgottenserver\src\protocolgame.h(33): note: see declaration of 'Tile'
1>c:\forgottenserver\src\game.cpp(760): error C2039: 'getHeight': is not a member of 'Tile'
1>c:\forgottenserver\src\protocolgame.h(33): note: see declaration of 'Tile'
1>c:\forgottenserver\src\game.cpp(762): error C2039: 'getHeight': is not a member of 'Tile'
1>c:\forgottenserver\src\protocolgame.h(33): note: see declaration of 'Tile'
1>c:\forgottenserver\src\game.cpp(764): error C2039: 'getHeight': is not a member of 'Tile'
1>c:\forgottenserver\src\protocolgame.h(33): note: see declaration of 'Tile'`

**Comment by Stoudemire** [comment]
height stack block esta funcionando correctamente

**Comment by joseluis2g** [comment]
Podrías probar los últimos cambios que realicé?
https://github.com/joseluis2g/my-nostalrius/commit/6193093b9cd56b262fe1960ff2105251bdf7ab7a

**Comment by Stoudemire** [comment]
> Podrías probar los últimos cambios que realicé?
> [6193093](https://github.com/joseluis2g/my-nostalrius/commit/6193093b9cd56b262fe1960ff2105251bdf7ab7a)

funciona perfecto!

**Comment by Stoudemire** [comment]
funciona en uh, en mana fluids no

**Comment by joseluis2g** [comment]
estas seguro? hiciste los cambios pertinentes? yo probé ambos

**Comment by Stoudemire** [comment]
Si, descargue los sources nuevos y remplaze fluids en data/actions/scripts/misc/fluids.lua

**Comment by joseluis2g** [comment]
okei, lo descrubrí 👍

**Comment by joseluis2g** [comment]
prueba con este cambio
https://github.com/joseluis2g/my-nostalrius/commit/2cdbbcd4d2d3b276429db4782bfc3f7a8568c3af

**Comment by Stoudemire** [comment]
al potear NPCS da este error
`Lua Script Error: [Action Interface]
data/actions/scripts/misc/fluids.lua:onUse
data/actions/scripts/misc/fluids.lua:65: attempt to call method 'addMana' (a nil value)
stack traceback:
        [C]: in function 'addMana'
        data/actions/scripts/misc/fluids.lua:65: in function <data/actions/scripts/misc/fluids.lua:27>`

**Comment by joseluis2g** [comment]
Subi todo al master y además hice un cambio:
https://github.com/joseluis2g/my-nostalrius/commit/eaadea60259cde6086ee22eeb82392289ac70a7a

**Comment by Stoudemire** [comment]
este error da al tratar de tirar un fluid al piso (potions,water, etc.) y tambien da al tratar de recoger agua del mar o de un pozo con una fluid, bucket, etc.
`Lua Script Error: [Action Interface]
data/actions/scripts/misc/fluids.lua:onUse
data/actions/scripts/misc/fluids.lua:52: attempt to call method 'isNpc' (a nil value)
stack traceback:
        [C]: in function 'isNpc'
        data/actions/scripts/misc/fluids.lua:52: in function <data/actions/scripts/misc/fluids.lua:27>`
