### ISSUE TITLE
errores en la compilacion

### ISSUE THREAD

**Issue by angeliker** [joseluis2g/my-nostalrius#4]
bueno aqui les dejo unos errores de la compilacion la verdad nose si solo es ami k me pasa pero no puedo compilar aki les dejo los errores mostrados en vs https://pastebin.com/Ssre4vhV

**Comment by angeliker** [comment]
Esk soy malo compilando en windows pero ya mejor hoy me cambio a linux si kieres cierra esto ya bro

**Comment by Stoudemire** [comment]
al compilar desde windows 10, mvs 2017 me da los mismos errores

**Comment by joseluis2g** [comment]
lo revisaré hoy.

**Comment by joseluis2g** [comment]
podrías probar esto: https://github.com/joseluis2g/my-nostalrius/commit/317b8be4a31a107bf23040ad85a394eb45ef980b

**Comment by Stoudemire** [comment]
**descargue el ultimo y al compilar da estos errores**
`1>c:\forgottenserver\src\commands.cpp(50): error C2653: 'Commands': is not a class or namespace name
1>c:\forgottenserver\src\commands.cpp(50): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\forgottenserver\src\commands.cpp(50): error C2146: syntax error: missing ';' before identifier 'defined_commands'
1>c:\forgottenserver\src\commands.cpp(50): error C2143: syntax error: missing ';' before '{'
1>c:\forgottenserver\src\commands.cpp(50): error C2447: '{': missing function header (old-style formal list?)
1>c:\forgottenserver\src\commands.cpp(61): error C2653: 'Commands': is not a class or namespace name
1>c:\forgottenserver\src\commands.cpp(62): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\forgottenserver\src\commands.cpp(64): error C2065: 'defined_commands': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(64): error C3312: no callable 'begin' function found for type 'unknown-type'
1>c:\forgottenserver\src\commands.cpp(64): error C3312: no callable 'end' function found for type 'unknown-type'
1>c:\forgottenserver\src\commands.cpp(65): error C2065: 'commandMap': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(65): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(65): error C2061: syntax error: identifier 'Command'
1>c:\forgottenserver\src\commands.cpp(67): warning C4508: 'Commands': function should return a value; 'void' return type assumed
1>c:\forgottenserver\src\commands.cpp(69): error C2653: 'Commands': is not a class or namespace name
1>c:\forgottenserver\src\commands.cpp(69): error C2523: '<Unknown>::~Commands': destructor tag mismatch
1>c:\forgottenserver\src\commands.cpp(70): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\forgottenserver\src\commands.cpp(70): error C2084: function 'int Commands(void)' already has a body
1>c:\forgottenserver\src\commands.cpp(61): note: see previous definition of 'Commands'
1>c:\forgottenserver\src\commands.cpp(71): error C2065: 'commandMap': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(71): error C3312: no callable 'begin' function found for type 'unknown-type'
1>c:\forgottenserver\src\commands.cpp(71): error C3312: no callable 'end' function found for type 'unknown-type'
1>c:\forgottenserver\src\commands.cpp(72): error C2065: 'it': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(76): error C2653: 'Commands': is not a class or namespace name
1>c:\forgottenserver\src\commands.cpp(92): error C2065: 'commandMap': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(93): error C3536: 'it': cannot be used before it is initialized
1>c:\forgottenserver\src\commands.cpp(93): error C2065: 'commandMap': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(98): error C2065: 'Command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(98): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(102): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(109): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(116): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(120): error C2039: 'addCommandTag': is not a member of 'Game'
1>c:\forgottenserver\src\monster.h(27): note: see declaration of 'Game'
1>c:\forgottenserver\src\commands.cpp(125): error C2653: 'Commands': is not a class or namespace name
1>c:\forgottenserver\src\commands.cpp(127): error C2065: 'commandMap': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(127): error C3312: no callable 'begin' function found for type 'unknown-type'
1>c:\forgottenserver\src\commands.cpp(127): error C3312: no callable 'end' function found for type 'unknown-type'
1>c:\forgottenserver\src\commands.cpp(128): error C2065: 'Command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(128): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(128): error C2065: 'it': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(129): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(130): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(131): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(134): error C2039: 'resetCommandTag': is not a member of 'Game'
1>c:\forgottenserver\src\monster.h(27): note: see declaration of 'Game'
1>c:\forgottenserver\src\commands.cpp(138): error C2653: 'Commands': is not a class or namespace name
1>c:\forgottenserver\src\commands.cpp(152): error C2065: 'commandMap': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(153): error C3536: 'it': cannot be used before it is initialized
1>c:\forgottenserver\src\commands.cpp(153): error C2065: 'commandMap': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(157): error C2065: 'Command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(157): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(158): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(167): error C2065: 'CommandFunc': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(167): error C2146: syntax error: missing ';' before identifier 'cfunc'
1>c:\forgottenserver\src\commands.cpp(167): error C2065: 'cfunc': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(167): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(168): error C2355: 'this': can only be referenced inside non-static member functions or non-static data member initializers
1>c:\forgottenserver\src\commands.cpp(168): error C2065: 'cfunc': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(170): error C2065: 'command': undeclared identifier
1>c:\forgottenserver\src\commands.cpp(189): error C2653: 'Commands': is not a class or namespace name
1>c:\forgottenserver\src\commands.cpp(243): error C2653: 'Commands': is not a class or namespace name
1>c:\forgottenserver\src\commands.cpp(296): error C2653: 'Commands': is not a class or namespace name`

**Comment by joseluis2g** [comment]
actualizo de inmediato el proyecto, siempre se me olvida eso 👍

**Comment by joseluis2g** [comment]
Podrías compilar la última actualización? 
https://github.com/joseluis2g/my-nostalrius/commit/1c49e814f2ed04dee5e757a983e5195a3751ed85

**Comment by joseluis2g** [comment]
Tambien actualicé el data.

**Comment by Stoudemire** [comment]
> Tambien actualicé el data.

Bien, no dio ningún error al compilar
