### ISSUE TITLE
Comando Reload

### ISSUE THREAD

**Issue by Stoudemire** [joseluis2g/my-nostalrius#9]
Error en consola al ejecutar el comando /reload 

`Lua Script Error: [TalkAction Interface]
data/talkactions/scripts/reload.lua:onSay
data/talkactions/scripts/reload.lua:63: attempt to call field 'reload' (a nil value)
stack traceback:
        [C]: in function 'reload'
        data/talkactions/scripts/reload.lua:63: in function <data/talkactions/scripts/reload.lua:48>`

**Comment by joseluis2g** [comment]
Acabo de actualizar los sources :)

**Comment by Stoudemire** [comment]
Si, ya actualice sources y data, me da ese error al ejecutar el comando

**Comment by joseluis2g** [comment]
Estas seguro que compilaste con estos cambios?
https://github.com/joseluis2g/my-nostalrius/commit/a9e4fd0d7d59bf3e0e6e8b43ad1681f3882a6cbd

**Comment by Stoudemire** [comment]
Ops, tienes razón, todo bien, funciona perfecto
